# Generated by Django 4.0.1 on 2022-02-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_students_intakeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='trackid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affairs.track'),
            preserve_default=False,
        ),
    ]
